const cardContexts = [
  "A black hole that only swallows the 'other' sock in the dryer.",
  "A ghost who haunts your house just to reorganize your spice rack.",
  "An alien invasion that is defeated by the smell of burnt toast.",
  "A UFO shaped like a giant, flying rotisserie chicken.",
  "The Grim Reaper taking a 'Mental Health Day' at a water park.",
  "A psychic who can only see what you ate for lunch three days ago.",
  "A parallel universe where everyone is made of wet cardboard.",
  "The Moon, but it has a very visible and very judgmental face.",
  "A portal to another dimension found at the bottom of a cereal box.",
  "A demon that possessed a toaster and now just burns 'HELP' into every slice.",
  "An astronaut who forgot the keys to the International Space Station.",
  "A planet where the currency is just awkward high-fives.",
  "Time travel, but you can only go back to 5 minutes ago.",
  "A supernova that sounds like a tiny, high-pitched 'pop.'",
  "The Loch Ness Monster trying to renew its driver's license.",
  "A star that is actually just a very bright, very lost firefly.",
  "A galaxy where gravity works sideways on Tuesdays.",
  "An Egyptian mummy who is really into 90s Grunge music.",
  "A Bigfoot sighting, but he’s wearing a tuxedo and holding a latte.",
  "The concept of 'Monday' manifesting as a physical, slimy blob.",
  "A squirrel with a PhD in Theoretical Physics.",
  "A pigeon that thinks it’s the reincarnation of Napoleon.",
  "A goldfish having a mid-life crisis in a 2-gallon bowl.",
  "A pack of wolves that only hunts for gluten-free snacks.",
  "A cat that has successfully filed its own taxes.",
  "An octopus trying to play eight different bagpipes at once.",
  "A spider that weaves 'passive-aggressive' messages into its web.",
  "A penguin who is a high-stakes poker champion in the underground arctic.",
  "A horse that is convinced it is actually a very tall dog.",
  "A snake wearing a tiny turtleneck sweater.",
  "A butterfly that causes hurricanes by sneezing in Ohio.",
  "A sloth that is addicted to energy drinks.",
  "A cow that only moos in a British accent.",
  "A bear that is terrified of the woods and prefers glamping.",
  "A crab that thinks the ocean is 'too salty' and wants to speak to a manager.",
  "A kangaroo that uses its pouch as a mobile taco stand.",
  "A bat with a severe fear of the dark.",
  "A lobster that believes it’s a world-class chef.",
  "A giraffe that is self-conscious about how long it takes for food to reach its stomach.",
  "A swarm of bees that only hums the 'Macarena.'",
  "A sentient block of cheddar cheese with existential dread.",
  "A pair of sneakers that screams every time you take a step.",
  "A library book that heckles you while you read it.",
  "A vacuum cleaner that is 'quietly judging' the state of your carpet.",
  "A refrigerator that hides the healthy food when you’re sad.",
  "A garden gnome that moves two inches closer every time you blink.",
  "A smartphone that deletes contacts it doesn't think are 'cool enough' for you.",
  "A chair that groans whenever someone sits on it.",
  "A microwave that enters a 'reflective state' and refuses to heat burritos.",
  "A toothbrush that is secretly recording a podcast about your hygiene.",
  "A lamp that only turns on when you tell it a secret.",
  "A mirror that shows you 10% more attractive, but only on Wednesdays.",
  "A mailbox that eats letters it finds 'boring.'",
  "A pillow that whispers spoilers for movies you haven't seen.",
  "A car that runs entirely on 'positive vibes' and broken dreams.",
  "A calculator that refuses to do math it finds 'too hard.'",
  "A ceiling fan that thinks it’s a helicopter pilot.",
  "A tube of toothpaste that is 90% air and 10% attitude.",
  "A remote control that hides in the couch out of spite.",
  "A pencil that only draws pictures of different types of potatoes.",
  "The exact moment you realize you left the stove on in a past life.",
  "A motivational speaker who is just a very loud cactus.",
  "A heavy metal band made entirely of librarians.",
  "Trying to explain the internet to a Victorian-era child.",
  "The smell of a library on a rainy Tuesday in 1994.",
  "A superhero whose only power is knowing exactly how much salt is in a soup.",
  "A mime who is actually trapped in a real invisible box.",
  "The feeling of 'stepping on a LEGO' but for your soul.",
  "A clown who takes his job way too seriously at a funeral.",
  "An Olympic athlete competing in 'Competitive Napping.'",
  "A secret society dedicated to finding the 'perfect' grape.",
  "A fashion show where everyone is wearing trash bags and confidence.",
  "A wedding where the 'Best Man' is a golden retriever.",
  "The world’s smallest violin playing a song about your student loans.",
  "A pirate who is terrified of the ocean and prefers the 'Lazy River.'",
  "A ninja who is unfortunately very loud and clumsy.",
  "A detective who solves crimes based on 'vibes' and 'astrology.'",
  "A knight in shining armor who is allergic to horses.",
  "A vampire who is a vegan and only drinks V8 juice.",
  "A zombie who is only interested in eating 'organic, free-range' brains.",
  "A professional wrestling match between a grandmother and a toaster.",
  "A weather report that predicts 'a 40% chance of raining meatballs.'",
  "A TED Talk delivered entirely in 'Simlish.'",
  "The sensation of your foot falling asleep during a job interview.",
  "A backup dancer who is clearly doing a different routine.",
  "A GPS that gives you life advice instead of directions.",
  "A beauty pageant for the world’s ugliest vegetables.",
  "The inner monologue of a pigeon watching a statue.",
  "A world where the 'Floor is Lava' is a legal requirement.",
  "A speed-dating event for mythical creatures.",
  "A heavy metal cover of 'Twinkle Twinkle Little Star.'",
  "The sheer audacity of a bird pooping on a freshly washed car.",
  "A reality show where the contestants are all just different types of bread.",
  "A museum dedicated to 'Things I Lost Under the Couch.'",
  "A barber who only knows how to give 'Mullets.'",
  "The awkward silence after a failed high-five.",
  "A volcano that erupts glitter and disappointment.",
  "A rock-paper-scissors tournament with $10 million on the line.",
  "A dragon who hoards 'Expired Coupons' instead of gold.",
  "The final boss of a video game is just your own reflection.",
  "A lifeguard for a bowl of lukewarm alphabet soup.",
  "A professional 'un-clutterer' who only removes things you actually need.",
  "A detective who only investigates crimes committed by inanimate objects.",
  "A travel agent for people who want to visit their own dreams.",
  "A personal trainer for house plants that refuse to grow straight.",
  "A lawyer representing a tree that was sued for 'looking suspicious.'",
  "A skydiving instructor who is actually just a very brave flying squirrel.",
  "A fashion designer who only works with 'recycled pizza boxes.'",
  "A brain surgeon who uses a 'magic 8-ball' for every diagnosis.",
  "A secret agent whose 'gadgets' are all just different types of fruit.",
  "A stunt double for a very lazy house cat.",
  "A wedding planner for two rival gangs of squirrels.",
  "A sommelier who can tell you exactly which faucet a glass of water came from.",
  "A librarian who shushes you even when you’re thinking too loudly.",
  "A ghost hunter who is actually just a ghost looking for his keys.",
  "A construction worker building a skyscraper out of popsicle sticks and hope.",
  "A pizza delivery driver who uses a catapult to ensure 'fast' delivery.",
  "A therapist for robots suffering from 'Identity Update Errors.'",
  "A barber who only gives haircuts to statues.",
  "A park ranger who is strictly there to prevent 'illegal picnicking.'",
  "A taco that is legally required to be 40% 'mystery.'",
  "A sentient burrito that is trying to negotiate for its own life.",
  "A bottle of ketchup that only comes out when you say 'please.'",
  "A bowl of cereal that screams when you pour milk on it.",
  "An ice cream cone that is actively trying to melt on your shoes.",
  "A sandwich that is 'too cool' to be eaten by you.",
  "A bag of chips that is 99% air and 1% concentrated salt.",
  "A fork that is going through a 'goth phase' and refuses to pick up vegetables.",
  "A blender that thinks it’s a heavy metal drummer.",
  "A stalk of broccoli that has a better social life than you do.",
  "A pizza topping that is just 'smaller, tinier pizzas.'",
  "A coffee mug that is judging your choice of creamer.",
  "A banana that is actually a very convincing yellow telephone.",
  "A salt shaker that is 'overwhelmed' by the pressure of its job.",
  "A waffle that is convinced it is a pancake in a grid-shaped prison.",
  "A steak that is so 'rare' it’s still trying to eat the side of mashed potatoes.",
  "A refrigerator that organizes food by 'vibes' rather than temperature.",
  "A loaf of bread that is 'rising' up against the baker.",
  "A jar of pickles that can only be opened by someone 'worthy.'",
  "A Thanksgiving turkey that has been invited as a guest, not the meal.",
  "Abraham Lincoln accidentally inventing the 'selfie stick.'",
  "A Viking who is terrified of the ocean and prefers 'Indoor Rowing.'",
  "A caveman trying to explain a 'subscription service' to his tribe.",
  "Cleopatra getting 'ghosted' by a messenger pigeon.",
  "A medieval knight who uses a 'pool noodle' instead of a sword.",
  "George Washington being caught wearing 'light-up sneakers' during the revolution.",
  "A samurai who is really into 'Competitive Knitting.'",
  "The Great Wall of China, but it’s made entirely of 'unopened mail.'",
  "A dinosaur who survived the asteroid by hiding in a very large 'bunker.'",
  "A Victorian lady trying to 'cancel' a rude telegram.",
  "An 80s aerobics instructor leading a workout for the Roman Senate.",
  "A pirate who lost his parrot and replaced it with a very confused chicken.",
  "The Discovery of Fire, but it was actually just a 'very spicy pepper.'",
  "A cowboy who rides a 'unicycle' instead of a horse.",
  "A Renaissance painter who only paints 'pictures of his own lunch.'",
  "A Greek philosopher who thinks the world is shaped like a 'donut.'",
  "A gold prospector who only finds 'discarded chewing gum.'",
  "A 1920s flapper girl trying to 'TikTok dance' at a jazz club.",
  "A Gladiator match where the weapons are 'squeaky hammers.'",
  "A time traveler who accidentally replaced the Mona Lisa with a 'drawing of a dog.'",
  "A Wi-Fi router that requires a 'blood sacrifice' to work.",
  "A 'Smart Home' that locks you out until you sing it a lullaby.",
  "A social media influencer who is just a 'sentient bag of flour.'",
  "A laptop that 'sighs' every time you open a new browser tab.",
  "A video game where the 'Easy Mode' is actually 'Impossible.'",
  "A GPS that takes you to the nearest 'emotional breakdown' instead of a gas station.",
  "A robot vacuum that has 'joined a cult' and only cleans in circles.",
  "A cryptocurrency that is backed entirely by 'lint found in pockets.'",
  "A Bluetooth speaker that only plays 'yodeling' at 3:00 AM.",
  "A 'Virtual Reality' headset that just shows you a 'slightly worse' version of your own room.",
  "An AI that is 'too depressed' to do your homework.",
  "A phone charger that only works if you hold your breath.",
  "A 'Meme' that has gained sentience and is running for local office.",
  "A computer mouse that is 'scared' of the cursor.",
  "A printer that smells 'fear' and jams when you’re in a hurry.",
  "A doorbell that 'insults your outfit' before letting people in.",
  "A digital watch that only tells you 'how much time you’ve wasted.'",
  "A toaster that is 'connected to the cloud' but only to argue with other toasters.",
  "A drone that is 'afraid of heights' and only flies three inches off the ground.",
  "A selfie that 'refuses to be saved' because it thinks it looks bad.",
  "A rainstorm where it only rains 'single shoes.'",
  "A world where the 'National Anthem' is just 5 minutes of 'kazoo noises.'",
  "A mountain that is actually just a 'really big, sleeping turtle.'",
  "A rainbow that is 'missing the color green' because it’s on strike.",
  "A cloud that is shaped like 'your own face' and is mocking you.",
  "A forest where the trees whisper 'embarrassing secrets' about you.",
  "A desert where the sand is actually 'crushed-up LEGOs.'",
  "A volcano that erupts 'nothing but polite compliments.'",
  "A moon that is 'shrinking' because it’s on a diet.",
  "A sun that 'wears sunglasses' because it’s too bright for itself.",
  "An ocean that is 'carbonated' and tastes like lemon-lime soda.",
  "A gravity-free zone that only affects 'your left arm.'",
  "A star that is 'burnt out' and just glows a faint 'mustard yellow.'",
  "A thunderstorm where the lightning is 'pink' and smells like 'bubblegum.'",
  "A world where 'sneezing' is the only form of legal currency.",
  "A bridge that 'asks you a riddle' before you can cross it.",
  "A statue that 'winks' at you when no one else is looking.",
  "A blizzard where it snows 'mashed potatoes.'",
  "A river that 'flows backwards' on the weekends.",
  "The concept of 'Gravity' getting 'laid off' due to budget cuts.",
  "A black hole that is currently being sued for 'unauthorized storage' of missing keys.",
  "A ghost who haunts your microwave just to beep exactly 1 second before it finishes.",
  "An alien civilization that worships a discarded 'fidget spinner' as a god.",
  "The Big Bang, but it was actually just a celestial sneeze.",
  "A planet where the trees grow 'fully cooked hot dogs' instead of leaves.",
  "A UFO that is powered entirely by the 'secondhand embarrassment' of humans.",
  "A parallel universe where everyone is a sentient balloon and 'popping' is a crime.",
  "The Moon, but it’s actually a giant, orbiting 'disco ball' that only turns on during parties.",
  "A portal to another dimension that only opens if you do a 'floss dance' perfectly.",
  "A demon that possessed a Roomba and now only cleans in the shape of pentagrams.",
  "An astronaut who accidentally left the 'stove on' back on Earth.",
  "A galaxy where gravity is 'pay-to-play' and you’re currently out of credits.",
  "A time traveler who went back to save the dinosaurs but ended up 'opening a taco stand.'",
  "A supernova that sounds like a tiny, squeaky 'rubber duck' when it explodes.",
  "The Loch Ness Monster trying to hide by wearing a 'very small snorkel.'",
  "A star that is actually just a 'very bright, very lost firefly' with an ego.",
  "A world where 'shadows' have their own jobs and 'quit' if you’re too boring.",
  "An Egyptian mummy who is really into 'Competitive Bowling.'",
  "A Bigfoot sighting, but he’s 'wearing a tutu' and practicing ballet in a clearing.",
  "The concept of 'Tuesday' manifesting as a physical, grumpy man in a bathrobe.",
  "A caveman trying to explain 'the cloud' to a very confused woolly mammoth.",
  "Abraham Lincoln accidentally 'butt-dialing' the Queen of England.",
  "A Viking who is 'allergic to beards' and has to remain perfectly shaven.",
  "A T-Rex trying to 'put on a hoodie' with its tiny, useless arms.",
  "A squirrel that has been 'deep-cover' for the CIA since the 1970s.",
  "A pigeon that is a 'certified pilot' but only for paper airplanes.",
  "A goldfish that is a 'conspiracy theorist' about the 'Giant Hand' that feeds it.",
  "A pack of wolves that only hunts for 'artisanal, small-batch granola.'",
  "A cat that has successfully 'cloned itself' just to have someone to ignore.",
  "An octopus trying to 'play 8 different instruments' but they’re all triangles.",
  "A spider that weaves 'passive-aggressive Yelp reviews' into its web.",
  "A penguin who is a 'high-stakes debt collector' for the polar bear mafia.",
  "A horse that is convinced it is actually a 'very large, very fast hamster.'",
  "A snake wearing a 'tiny tuxedo' for its own wedding to a garden hose.",
  "A butterfly that causes 'mild inconveniences' by flapping its wings in Ohio.",
  "A sloth that is a 'professional speed-typer' in its own mind.",
  "A cow that moos in 'perfect iambic pentameter.'",
  "A bear that is 'terrified of berries' and only eats takeout pizza.",
  "A crab that thinks the ocean is 'too wet' and wants to live in a desert.",
  "A kangaroo that uses its pouch as a 'mobile podcast studio.'",
  "A sentient block of tofu that is 'having a mid-life crisis' and wants to be a steak.",
  "A pair of jeans that 'audibly groans' every time you eat a large meal.",
  "A library book that 'heckles you' for skipping the boring chapters.",
  "A vacuum cleaner that is 'going through a goth phase' and only sucks up black dust.",
  "A refrigerator that 'hides the beer' when it thinks you’ve had enough.",
  "A garden gnome that 'moves two inches closer' every time you say a curse word.",
  "A smartphone that 'deletes your ex's number' out of pure spite.",
  "A chair that 'judges your posture' by whispering 'wow, okay' when you sit.",
  "A microwave that enters a 'silent protest' and refuses to pop popcorn.",
  "A toothbrush that is 'writing a tell-all memoir' about your dental hygiene.",
  "A lamp that only turns on when you tell it 'a secret you’ve never told anyone.'",
  "A mirror that shows you '10% more muscular' but only if you’re wearing a hat.",
  "A mailbox that 'eats bills' and only delivers 'hand-written love letters.'",
  "A pillow that 'whispers spoilers' for the dream you’re about to have.",
  "A car that runs entirely on 'the power of friendship' and 'premium gasoline.'",
  "A calculator that 'refuses to do math' that it finds 'unethical.'",
  "A ceiling fan that thinks it’s an 'undercover agent' for the FBI.",
  "A tube of toothpaste that is '90% attitude' and '10% mint.'",
  "A remote control that 'teleports' to the kitchen every time you look away.",
  "A pencil that only draws 'portraits of different types of cheese.'",
  "A Wi-Fi router that requires a 'signed apology' to start working again.",
  "A motivational speaker who is just a 'very loud, very angry cactus.'",
  "A heavy metal band made entirely of 'librarians' who only scream about late fees.",
  "Trying to explain 'TikTok' to a Victorian child until they physically dissolve.",
  "The smell of 'a brand new car' but it’s actually just 'concentrated despair.'",
  "A superhero whose only power is 'knowing exactly how many beans are in any jar.'",
  "A mime who is 'actually trapped' in a real, invisible, soundproof box.",
  "The feeling of 'stepping on a LEGO' but it’s happening to your soul.",
  "A clown who is the 'CEO of a major investment bank' and takes it very seriously.",
  "An Olympic athlete competing in 'Extreme Sarcasm.'",
  "A secret society dedicated to 'finding the remote' that fell behind the couch.",
  "A fashion show where everyone is wearing 'bubble wrap' and 'shame.'",
  "A wedding where the 'Priest' is a very confused Golden Retriever.",
  "The world’s smallest violin playing a song about 'your WiFi being slightly slow.'",
  "A pirate who is 'scared of parrots' and uses a 'rubber chicken' instead.",
  "A ninja who is 'unfortunately very loud' and wears 'squeaky shoes.'",
  "A detective who solves crimes by 'asking the victim’s ghost for a hint.'",
  "A knight in shining armor who is 'allergic to metal' and wears 'cardboard.'",
  "A vampire who is a 'vegan' and only drinks 'V8 juice' and 'red Gatorade.'",
  "A zombie who is 'only interested in eating' people who don't recycle.",
  "A professional wrestling match between a 'grandma' and a 'sentient toaster.'",
  "A weather report that predicts 'a 40% chance of raining marshmallows.'",
  "A TED Talk delivered entirely in 'kazoo noises' and 'aggressive pointing.'",
  "The sensation of 'your foot falling asleep' and starting a new life without you.",
  "A backup dancer who is clearly 'doing a different routine' from a different era.",
  "A GPS that gives you 'life advice' and 'judges your driving music.'",
  "A beauty pageant for the 'world’s most average-looking potatoes.'",
  "The inner monologue of a 'statue' watching pigeons land on it.",
  "A world where the 'Floor is Lava' is a mandatory government drill.",
  "A speed-dating event where everyone is 'disguised as a different fruit.'",
  "A heavy metal cover of 'The Wheels on the Bus' that is surprisingly good.",
  "The sheer audacity of a 'squirrel' looking you in the eye while stealing a nut.",
  "A reality show where the contestants are all 'different types of bread.'",
  "A museum dedicated to 'Things I Dropped in the Toilet by Accident.'",
  "A barber who only knows how to give 'The George Washington' haircut.",
  "The awkward silence after 'realizing you waved at a stranger.'",
  "A volcano that erupts 'nothing but glitter' and 'mild disappointment.'",
  "A rock-paper-scissors tournament with 'the fate of the moon' on the line.",
  "A dragon who hoards 'expired coupons' and 'rejected screenplays.'",
  "The final boss of a video game is just 'you, but with a slightly larger hat.'",
  "A seagull who is a food critic and only reviews stolen french fries.",
  "A seagull wearing a tiny captain's hat, convinced it owns the pier.",
  "A seagull that can only scream in 'Auto-Tune.'",
  "A seagull who is currently in a legal battle over a discarded taco.",
  "A seagull who thinks it’s an undercover pigeon.",
  "A seagull that only steals 'gluten-free' snacks.",
  "A seagull who is a professional wedding crasher and steals the ring.",
  "A seagull that leads a secret underground 'Boardwalk Mafia.'",
  "A seagull who is terrified of the ocean and prefers public pools.",
  "A seagull that tries to 'pay' for a hot dog with a shiny pebble.",
  "A seagull who is a world-class beatboxer.",
  "A seagull who thinks the 'Keep Off' signs are actually personal invitations.",
  "A seagull that only flies in 'perfect formation' with itself.",
  "A seagull who is a fashion icon for wearing a plastic six-pack ring as a necklace.",
  "A seagull that thinks it’s a parrot and keeps saying 'Polly want a pretzel.'",
  "A seagull who is a high-stakes negotiator for ice cream cones.",
  "A seagull that is currently 'shadowing' a tourist to learn their habits.",
  "A seagull who is a 'sovereign citizen' and doesn't believe in beach rules.",
  "A seagull that only poops on cars that aren't 'parked correctly.'",
  "A seagull who is a 'wellness coach' for other birds.",
  "A seagull that is addicted to the 'ASMR' sound of a chip bag opening.",
  "A seagull who is a 'sentient alarm clock' that only goes off at 4:00 AM.",
  "A seagull who thinks it’s a 'drone' and makes whirring noises.",
  "A seagull that is 'gatekeeping' the best trash can in the city.",
  "A seagull who is a 'professional lurker' behind sandcastles.",
  "A seagull that is 'cosplaying' as an albatross.",
  "A seagull who is a 'stand-up comedian' whose only joke is screaming.",
  "A seagull that is 'offended' by the quality of your sandwich.",
  "A seagull who is a 'secret admirer' of a specific lifeguard.",
  "A seagull that is 'training' a squirrel to be its apprentice.",
  "A seagull who is a 'landlord' for a specific section of the boardwalk.",
  "A seagull that only steals 'spicy' chips to feel alive.",
  "A seagull who is a 'retired pirate' with a tiny wooden leg.",
  "A seagull that thinks it’s a 'diva' and won't fly for less than a full pizza.",
  "A seagull who is a 'private investigator' for missing flip-flops.",
  "A seagull that is 'practicing' its dive-bombing for the Olympics.",
  "A seagull who is a 'ghostwriter' for bird-themed poetry.",
  "A seagull that is 'obsessed' with the reflection in your sunglasses.",
  "A seagull who is a 'bouncer' for a popular picnic spot.",
  "A seagull that is 'judging' your lack of sunscreen.",
  "A seagull who is a 'professional photobomber' for tourist selfies.",
  "A seagull that is 'convinced' it can speak human but only says 'MINE.'",
  "A seagull who is a 'survivalist' living off discarded churros.",
  "A seagull that is 'trying out' for a role in a remake of 'The Birds.'",
  "A seagull who is a 'personal shopper' for other gulls.",
  "A seagull that is 'allergic' to fish and only eats nachos.",
  "A seagull who is a 'tour guide' who only shows people where the trash is.",
  "A seagull that is 'writing a blog' about the best beaches for theft.",
  "A seagull who is a 'professional napper' on top of moving cars.",
  "A seagull that is 'holding a grudge' against a specific toddler.",
  "A seagull who is a 'yoga instructor' specializing in 'The Perch.'",
  "A seagull that is 'distracted' by the shiny foil on a gum wrapper.",
  "A seagull who is a 'hacker' who only wants to steal your Wi-Fi password.",
  "A seagull that is 'convinced' it is the reincarnation of a sea captain.",
  "A seagull who is a 'luxury travel agent' for migrating birds.",
  "A seagull that is 'scared' of crabs and only lands on dry land.",
  "A seagull who is a 'professional whistler' but only off-key.",
  "A seagull that is 'protecting' a specific piece of driftwood.",
  "A seagull who is a 'critic' of sandcastle architecture.",
  "A seagull that is 'trying' to start a flash mob on the pier.",
  "A seagull who is a 'detective' looking for the 'Great French Fry Thief.'",
  "A seagull that is 'obsessed' with the sound of a soda can opening.",
  "A seagull who is a 'bodyguard' for a very small child's lollipop.",
  "A seagull that is 'learning' to surf on a piece of Styrofoam.",
  "A seagull who is a 'fashionista' wearing a discarded mask as a cape.",
  "A seagull that is 'waiting' for the perfect moment to steal your hat.",
  "A seagull who is a 'historian' of the local boardwalk.",
  "A seagull that is 'trying' to befriend a pelican for the perks.",
  "A seagull who is a 'professional screeners' for horror movies.",
  "A seagull that is 'convinced' your car is its long-lost mother.",
  "A seagull who is a 'life coach' telling everyone to 'just fly away.'",
  "A seagull that is 'disturbed' by the presence of a kite.",
  "A seagull who is a 'stuntman' for high-speed pizza snatching.",
  "A seagull that is 'judging' your choice of beach towel.",
  "A seagull who is a 'poet' who only writes about 'The Great Salt.'",
  "A seagull that is 'convinced' it is invisible when it closes its eyes.",
  "A seagull who is a 'personal trainer' for overweight pigeons.",
  "A seagull that is 'trying' to open a clamshell with a plastic fork.",
  "A seagull who is a 'celebrity' in the world of birdwatching.",
  "A seagull that is 'scared' of its own shadow on the sand.",
  "A seagull who is a 'bouncer' at the local fish market.",
  "A seagull that is 'obsessed' with the color neon orange.",
  "A seagull who is a 'detective' investigating a missing donut.",
  "A seagull that is 'trying' to hitch a ride on a ferry.",
  "A seagull who is a 'motivational speaker' for birds with clipped wings.",
  "A seagull that is 'distracted' by a laser pointer on the beach.",
  "A seagull who is a 'professional heckler' at beach volleyball games.",
  "A seagull that is 'convinced' it is a secret agent for the penguins.",
  "A seagull who is a 'luxury real estate agent' for nesting spots.",
  "A seagull that is 'trying' to mimic the sound of a jet engine.",
  "A seagull who is a 'personal chef' for a very picky crow.",
  "A seagull that is 'scared' of umbrellas and thinks they are giant flowers.",
  "A seagull who is a 'professional collector' of bottle caps.",
  "A seagull that is 'trying' to use a touchscreen with its beak.",
  "A seagull who is a 'critic' of tourist fashion.",
  "A seagull that is 'convinced' it can swim better than a dolphin.",
  "A seagull who is a 'professional witness' for beach crimes.",
  "A seagull that is 'obsessed' with the smell of sunblock.",
  "A seagull who is a 'detective' looking for the 'Legendary Golden Fry.'",
  "A seagull that is 'trying' to start its own religion based on 'The Great Scoop.'",
  "A pony who thinks it’s a unicorn and wears a traffic cone on its head.",
  "A pony who is a professional 'emotional support animal' for a grizzly bear.",
  "A pony that only gallops in 'slow motion' for dramatic effect.",
  "A pony who is a high-stakes 'Competitive Eater' of carrots.",
  "A pony who thinks it’s a 'show dog' and tries to sit and stay.",
  "A pony that only responds to the name 'Sir Trots-a-Lot.'",
  "A pony who is a 'fashionista' with a mane full of glitter and bows.",
  "A pony that is 'convinced' it is a racehorse trapped in a tiny body.",
  "A pony who is a 'professional escape artist' from petting zoos.",
  "A pony that only eats 'organic, non-GMO' hay.",
  "A pony who is a 'detective' specializing in missing sugar cubes.",
  "A pony who thinks it’s a 'police horse' and tries to pull over cyclists.",
  "A pony that is 'obsessed' with its own reflection in the water bucket.",
  "A pony who is a 'yoga instructor' specializing in 'The Grazing Pose.'",
  "A pony that is 'scared' of its own tail and tries to outrun it.",
  "A pony who is a 'professional napper' in the middle of a parade.",
  "A pony that only listens to 'smooth jazz' while being brushed.",
  "A pony who is a 'luxury travel agent' for other barnyard animals.",
  "A pony that is 'convinced' it can fly if it jumps high enough.",
  "A pony who is a 'beauty blogger' specializing in hoof polish.",
  "A pony that is 'addicted' to the sound of an apple being crunched.",
  "A pony who is a 'professional photobomber' for wedding photos.",
  "A pony that thinks it’s a 'mountain goat' and tries to climb trees.",
  "A pony who is a 'bouncer' for the stable's VIP section.",
  "A pony that is 'gatekeeping' the best patch of clover.",
  "A pony who is a 'professional lurker' in the background of selfies.",
  "A pony that is 'cosplaying' as a zebra with white paint.",
  "A pony who is a 'standard comedian' whose only joke is 'neigh-ing.'",
  "A pony that is 'offended' by the quality of its salt lick.",
  "A pony who is a 'secret admirer' of a specific tractor.",
  "A pony that is 'training' a goat to be its squire.",
  "A pony who is a 'landlord' for the local barn.",
  "A pony that only gallops when 'The Imperial March' is playing.",
  "A pony who is a 'retired knight' with a tiny wooden shield.",
  "A pony that thinks it’s a 'diva' and won't walk for less than a gold-plated carrot.",
  "A pony who is a 'private investigator' for stolen horsehair.",
  "A pony that is 'practicing' its dressage for the Olympics.",
  "A pony who is a 'ghostwriter' for pony-themed romance novels.",
  "A pony that is 'obsessed' with the sound of a zipper.",
  "A pony who is a 'bouncer' at the local meadow.",
  "A pony that is 'judging' your lack of riding boots.",
  "A pony who is a 'professional photobomber' for kids' birthday parties.",
  "A pony that is 'convinced' it can speak human but only says 'HAY.'",
  "A pony who is a 'survivalist' living off stolen picnic baskets.",
  "A pony that is 'trying out' for a role in a remake of 'My Little Pony.'",
  "A pony who is a 'personal shopper' for other horses.",
  "A pony that is 'allergic' to grass and only eats oat cookies.",
  "A pony who is a 'tour guide' who only shows people where the apples are.",
  "A pony that is 'writing a blog' about the best stables in the county.",
  "A pony who is a 'professional napper' standing up.",
  "A pony that is 'holding a grudge' against a specific donkey.",
  "A pony who is a 'yoga instructor' specializing in 'The Downward Horse.'",
  "A pony that is 'distracted' by the shiny buckles on a saddle.",
  "A pony who is a 'hacker' who only wants to order more carrots online.",
  "A pony that is 'convinced' it is the reincarnation of a war horse.",
  "A pony who is a 'luxury travel agent' for trail rides.",
  "A pony that is 'scared' of chickens and thinks they are tiny dinosaurs.",
  "A pony who is a 'professional whistler' through its nostrils.",
  "A pony that is 'protecting' a specific fence post.",
  "A pony who is a 'critic' of stable architecture.",
  "A pony that is 'trying' to start a flash mob in the pasture.",
  "A pony who is a 'detective' looking for the 'Great Hay Thief.'",
  "A pony that is 'obsessed' with the sound of a gate opening.",
  "A pony who is a 'bodyguard' for a very small kitten.",
  "A pony that is 'learning' to dance to country music.",
  "A pony who is a 'fashionista' wearing a floral wreath as a crown.",
  "A pony that is 'waiting' for the perfect moment to steal your apple.",
  "A pony who is a 'historian' of the local farm.",
  "A pony that is 'trying' to befriend a cow for the extra milk.",
  "A pony who is a 'professional whinner' for dramatic movies.",
  "A pony that is 'convinced' your truck is its long-lost father.",
  "A pony who is a 'life coach' telling everyone to 'just keep trotting.'",
  "A pony that is 'disturbed' by the presence of a balloon.",
  "A pony who is a 'stuntman' for high-speed carrot snatching.",
  "A pony that is 'judging' your choice of riding helmet.",
  "A pony who is a 'poet' who only writes about 'The Golden Oat.'",
  "A pony that is 'convinced' it is invisible when it stands perfectly still.",
  "A pony who is a 'personal trainer' for lazy sheep.",
  "A pony that is 'trying' to open a gate with its teeth.",
  "A pony who is a 'celebrity' in the world of equestrian sports.",
  "A pony that is 'scared' of its own shadow in the moonlight.",
  "A pony who is a 'bouncer' at the local county fair.",
  "A pony that is 'obsessed' with the color bright pink.",
  "A pony who is a 'detective' investigating a missing horseshoe.",
  "A pony that is 'trying' to hitch a ride on a trailer.",
  "A pony who is a 'motivational speaker' for horses with stage fright.",
  "A pony that is 'distracted' by a butterfly in the field.",
  "A pony who is a 'professional heckler' at dressage competitions.",
  "A pony that is 'convinced' it is a secret agent for the unicorns.",
  "A pony who is a 'luxury real estate agent' for paddock spots.",
  "A pony that is 'trying' to mimic the sound of a galloping herd.",
  "A pony who is a 'personal chef' for a very picky pig.",
  "A pony that is 'scared' of rain and thinks the sky is leaking.",
  "A pony who is a 'professional collector' of ribbons.",
  "A pony that is 'trying' to use a tablet with its nose.",
  "A pony who is a 'critic' of farm fashion.",
  "A pony that is 'convinced' it can run faster than a train.",
  "A pony who is a 'professional witness' for barnyard disputes.",
  "A pony that is 'obsessed' with the smell of peppermint.",
  "A pony who is a 'detective' looking for the 'Legendary Golden Carrot.'",
  "A seagull who acts as a high-stakes negotiator for the last corner of a pizza crust.",
  "A sentient parking meter that accepts 'genuine compliments' as a form of payment.",
  "A ghost who haunts your laundry room just to turn all your white socks slightly gray.",
  "A squirrel that is currently 'auditing' your birdfeeder for possible tax evasion.",
  "A microwave that enters a 'reflective state' and refuses to heat leftovers it finds 'uninspiring.'",
  "A seagull wearing a tiny headset, directing a fleet of pigeons like an air traffic controller.",
  "A smartphone that 'deletes your ex's number' out of pure, unadulterated spite.",
  "A professional wrestler whose entire persona is based on being a 'very polite accountant.'",
  "A seagull that can only scream in perfectly pitched 'Auto-Tune'.",
  "A garden gnome that moves two inches closer every time you blink.",
  "A vacuum cleaner that is 'going through a goth phase' and only sucks up black dust.",
  "A pony who thinks it’s a unicorn and wears a bright orange traffic cone on its head.",
  "A seagull who is a food critic and only reviews stolen french fries from tourists.",
  "A toaster that is 'connected to the cloud' but only to argue with other toasters.",
  "A squirrel with a PhD in Theoretical Physics and a very small chalkboard.",
  "A spider that weaves 'passive-aggressive Yelp reviews' into its web.",
  "A seagull who is a 'sovereign citizen' and doesn't believe in local beach rules.",
  "A pony that only gallops in 'slow motion' to make every entrance feel dramatic.",
  "A mirror that shows you 10% more muscular, but only if you are wearing a hat.",
  "A seagull that tries to 'pay' for a boardwalk hot dog with a particularly shiny pebble.",
  "A laptop that 'sighs' audibly every time you open a new browser tab.",
  "A penguin who is a high-stakes poker champion in the underground arctic.",
  "A seagull who is a professional wedding crasher and specifically targets the rings.",
  "A sentient block of cheddar cheese suffering from severe existential dread.",
  "A pony that is 'convinced' it can fly if it just jumps high enough from a hill.",
  "A seagull that is 'addicted' to the ASMR sound of a crinkling chip bag.",
  "A refrigerator that hides the healthy food whenever it senses you are sad.",
  "A seagull who is a 'wellness coach' for other birds, teaching them how to 'let go' of bread.",
  "A pony who is a 'beauty blogger' specializing in high-gloss hoof polish.",
  "A seagull that is 'gatekeeping' the best trash can in the city from other gulls.",
  "A mailbox that eats letters it finds 'boring' and refuses to deliver them.",
  "A pony that only listens to 'smooth jazz' while being brushed in the morning.",
  "A seagull who is a 'stand-up comedian' whose entire set consists of screaming.",
  "A tube of toothpaste that is 90% attitude and only 10% actual mint.",
  "A seagull who is a 'private investigator' for missing flip-flops on the shore.",
  "A pony who thinks it’s a 'show dog' and tries to sit and stay for treats.",
  "A seagull that is 'obsessed' with the reflection in your designer sunglasses.",
  "A calculator that refuses to do math it finds 'too hard' or 'unethical'.",
  "A seagull who is a 'professional photobomber' for every tourist selfie.",
  "A pony that is 'scared' of its own tail and tries to outrun it daily.",
  "A seagull that is 'writing a blog' about the best beach locations for theft.",
  "A chair that 'judges your posture' by whispering 'wow, okay' when you sit down.",
  "A seagull who is a 'tour guide' who only shows people where the best trash is.",
  "A pony who is a 'luxury travel agent' for other barnyard animals.",
  "A seagull that is 'holding a grudge' against a specific toddler who dropped a fry.",
  "A ceiling fan that thinks it’s an 'undercover agent' for the FBI.",
  "A seagull who is a 'yoga instructor' specializing in 'The Perch' pose.",
  "A pony that is 'cosplaying' as a zebra using white house paint.",
  "A seagull that is 'convinced' it is invisible as long as it closes its eyes.",
  "A toothbrush that is secretly recording a podcast about your dental hygiene.",
  "A seagull who is a 'personal trainer' for overweight city pigeons.",
  "A pony that is 'distracted' by the shiny buckles on a leather saddle.",
  "A seagull that is 'trying' to start a flash mob on the pier during sunset.",
  "A remote control that 'teleports' to the kitchen every time you look away.",
  "A seagull who is a 'detective' looking for the 'Legendary Golden Fry'.",
  "A pony that is 'convinced' your truck is actually its long-lost father.",
  "A seagull that is 'learning' to surf on a discarded piece of Styrofoam.",
  "A pillow that 'whispers spoilers' for the dream you are about to have.",
  "A seagull who is a 'historian' of the local boardwalk's various snack shops.",
  "A pony who is a 'professional napper' even during the middle of a parade.",
  "A seagull that is 'convinced' it can speak human but only ever says 'MINE'.",
  "A car that runs entirely on 'positive vibes' and very expensive gasoline.",
  "A seagull who is a 'stuntman' for high-speed, precision pizza snatching.",
  "A pony that is 'trying' to open a heavy gate with its teeth out of boredom.",
  "A seagull that is 'judging' your lack of sunscreen on a very hot day.",
  "A lamp that only turns on when you tell it a secret you've never told anyone.",
  "A seagull who is a 'poet' who only writes about the majesty of the 'Great Salt'.",
  "A pony who is a 'life coach' telling everyone to 'just keep trotting'.",
  "A seagull that is 'obsessed' with the sound of a soda can being opened.",
  "A world where the 'National Anthem' is just five minutes of kazoo noises.",
  "A seagull who is a 'bouncer' for a very popular picnic spot on the grass.",
  "A pony that is 'scared' of chickens and thinks they are tiny dinosaurs.",
  "A seagull that is 'convinced' it can swim much better than a dolphin.",
  "A GPS that gives you 'life advice' instead of actual driving directions.",
  "A seagull who is a 'professional collector' of colorful plastic bottle caps.",
  "A pony that is 'obsessed' with the color bright pink for its accessories.",
  "A seagull that is 'trying' to use a touchscreen phone with its beak.",
  "A motivational speaker who is just a 'very loud, very angry cactus'.",
  "A seagull who is a 'luxury real estate agent' for prime nesting spots.",
  "A pony that is 'trying' to hitch a ride on the back of a horse trailer.",
  "A seagull that is 'scared' of umbrellas and thinks they are giant flowers.",
  "A knight in shining armor who is 'allergic to metal' and wears cardboard.",
  "A seagull who is a 'professional witness' for various beach-related crimes.",
  "A pony who is a 'detective' investigating a missing horseshoe in the barn.",
  "A seagull that is 'obsessed' with the smell of generic sunblock.",
  "A superhero whose only power is knowing exactly how many beans are in a jar.",
  "A seagull who is a 'personal chef' for a very picky, high-maintenance crow.",
  "A pony that is 'scared' of rain because it thinks the sky is leaking.",
  "A seagull that is 'trying' to start its own religion based on 'The Great Scoop'.",
  "A zombie who is only interested in eating people who don't recycle.",
  "A seagull who is a 'motivational speaker' for birds with clipped wings.",
  "A pony that is 'distracted' by a single butterfly in the middle of a field.",
  "A seagull that is 'convinced' your car is its long-lost biological mother.",
  "A heavy metal band made entirely of librarians screaming about late fees.",
  "A seagull who is a 'critic' of the latest tourist beach fashions.",
  "A pony that is 'convinced' it can run significantly faster than a train.",
  "A seagull that is 'scared' of its own shadow on the wet sand.",
  "A volcano that erupts nothing but glitter and mild disappointment.",
  "A seagull who is a 'professional heckler' at beach volleyball games.",
  "A pony who is a 'detective' looking for the 'Legendary Golden Carrot'."
];
