const gamePrompts = [
    { category: "COSMIC", text: "What is the real reason aliens refuse to make contact with Earth?" },
    { category: "COSMIC", text: "What's the last thing you'd expect to find at the center of a Black Hole?" },
    { category: "ANIMALS", text: "What's the first thing a squirrel would say if it could talk?" },
    { category: "ANIMALS", text: "What is the secret underground society of pigeons planning right now?" },
    { category: "OBJECTS", text: "What is your toaster secretly whispering to the microwave at night?" },
    { category: "OBJECTS", text: "If your couch could talk, what's the most embarrassing thing it would reveal?" },
    { category: "TECH", text: "What's the next 'smart' feature that absolutely no one asked for?" },
    { category: "TECH", text: "What does your Wi-Fi router do when it's 'rebooting' for 10 minutes?" },
    { category: "FOOD", text: "What is the secret 'mystery ingredient' in every boardwalk hot dog?" },
    { category: "FOOD", text: "If pizza had a soul, what would it be most afraid of?" },
    { category: "SEAGULLS", text: "What is the ultimate goal of the Seagull Mafia?" },
    { category: "SEAGULLS", text: "What's the most high-stakes thing a seagull has ever successfully stolen?" },
    { category: "PONIES", text: "What is a pony actually thinking while wearing a pink tutu?" },
    { category: "PONIES", text: "What's the first rule of the 'Secret Underground Pony Club'?" },
    { category: "HISTORY", text: "What was the real reason the Great Wall of China was built?" },
    { category: "HISTORY", text: "What is the one invention Abraham Lincoln tried to hide from the world?" },
    { category: "PARANORMAL", text: "What does a ghost do for fun when it's not haunting people?" },
    { category: "PARANORMAL", text: "If you summoned a demon by accident, what would it probably ask for first?" },
    { category: "ABSURD", text: "What's the worst possible thing to hear right before a first date?" },
    { category: "ABSURD", text: "If the floor actually became lava, what's the first thing you'd grab?" },
    { category: "CAREER", text: "What's the real reason your boss is always in a 'meeting'?" },
    { category: "CAREER", text: "What's the most useless job title in a futuristic cyberpunk office?" },
    { category: "BIOLOGICAL", text: "What's the strangest thing human evolution will give us in 10,000 years?" },
    { category: "SURREAL", text: "If dreams were taxable, what would be the most expensive one to have?" },
    { category: "FINAL BOSS", text: "What is the ultimate 'Final Boss' of an average Monday morning?" }
];
